
########################
#
# 29CM PRODUCT PROJECT
#
########################



server:
  port: 9093
  servlet:
    context-path: /
spring:
  application:
    name: 29CM
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:test
      driver-class-name: org.h2.Driver
      name: sa
      password:
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
